name: test-fortran

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

env:
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  test:
    name: test fortran (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        gcc_v: [9]
        include:
          - os: ubuntu-latest
            os-arch: linux-x86_64

          - os: macos-latest
            os-arch: macos-x86_64

          - os: windows-latest
            os-arch: windows-x86_64
            exe: .exe
            cmake-generator: "-G Ninja"

    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GFortran macOS
        if: contains(matrix.os, 'macos')
        run: |
          ln -s /usr/local/bin/gfortran-${GCC_V} /usr/local/bin/gfortran
          which gfortran-${GCC_V}
          which gfortran

      - name: Install GFortran Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}

      - name: CMake configure
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. ${{ matrix.cmake-generator }} -DBUILD_EXAMPLES=ON -DBUILD_FASTSCAPELIB_SHARED=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build library and examples
        shell: bash
        run: |
          cd build
          cmake --build .

      - name: Run Fan example
        shell: bash
        run: |
          cd build/examples
          ./Fan${{ matrix.exe }}
