name: test-fortran

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  test:
    name: test fortran (${{ matrix.cfg.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            compiler: clang

          - os: ubuntu-latest
            compiler: gcc

          - os: ubuntu-latest
            compiler: clang

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CMake configure
        shell: bash -l {0}
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_EXAMPLES=ON -DBUILD_FASTSCAPELIB_SHARED=ON -DCMAKE_BUILD_TYPE=Debug
      - name: Build library and examples
        shell: bash -l {0}
        run: |
          cmake --build .
      - name: Run Fan example
        shell: bash -l {0}
        run: |
          cd examples
          ./Fan
