name: test-python

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  gcc-build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install numpy scikit-build ninja

      - name: Set Compiler (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo "FC=gfortran" >> $GITHUB_ENV
          echo "CC=gcc" >> $GITHUB_ENV

      - name: Set Compiler (MacOS)
        if: contains(matrix.os, 'macos')
        run: |
          echo "FC=gfortran-9" >> $GITHUB_ENV
          echo "CC=gcc-9" >> $GITHUB_ENV

      - name: Build and install Python bindings
        run: python -m pip install . -v --no-build-isolation --no-deps --ignore-installed --no-cache-dir

      - name: Test import Python module
        run: python -c "import sys; sys.path.pop(0); import fastscapelib_fortran"
